#!/bin/bash

source parms

for d in processor*; do
    cp 0/U $d/0/U; cp 0/p $d/0/p
    test -f $d/constant/flowParms && rm $d/constant/flowParms
done

mpirun -np $nproc writeMeshObj -constant -parallel
parentdir="$(dirname `pwd`)"
python3 /home/gsolemari/unsaturated/sample.py $parentdir flow flow_b

echo Running simpleHeleShaw
mpirun -np $nproc simpleHeleShaw > logFlow -parallel
echo Finished running simpleHeleShaw

cp processor0/constant/flowParms constant/
for d in processor*; do
    test -f $d/constant/flowParms && rm $d/constant/flowParms
done
